#!/usr/bin/env python3
"""
rtraw_to_esd.py
===============
Stage -1b: reconstruct rtraw -> ESD with the official junosw chain
(`${TUTORIALROOT}/share/tut_rtraw2rec.py`, CVMFS J26.1.1), optionally
overlaying OMILRECV2 (the optimized vertex/energy algorithm).

Pure orchestration: this script only writes a bash wrapper that sources
the environments and runs tut_rtraw2rec with the frozen flag set from
config/paths.py (verbatim from the validated invocation — do not edit
flags casually), then verifies the output contains
Event/CdVertexRecOMILREC entries (the tree MySimpleTag reads downstream).

Usage:
    python3 src/rtraw_to_esd.py 10110 --input-list <txt> \
        --out-root <ESD root file> --evtmax 100 --impl omilrecv2 \
        --work-dir <dir for wrapper+logs>
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

_PROJ = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJ))
import config.paths as P  # noqa: E402


def build_wrapper(impl: str, input_list: str, out_root: str,
                  evtmax: int) -> str:
    overlay = ""
    if impl == "omilrecv2":
        overlay = f"""
# OMILRECV2 overlay: registers the optimized algorithm in place of OMILREC
# (via InstallArea/python/sitecustomize.py shadow module)
source "{P.OMILRECV2_SETUP}"
"""
    elif impl != "baseline":
        raise SystemExit(f"[Error] unknown impl {impl!r}")

    flags = " ".join(P.RECON_FLAGS)  # $TUTORIALROOT entries stay literal
    return f"""#!/bin/bash
# Auto-generated by rtraw_to_esd.py — do not edit
set -e
source "{P.CVMFS_SETUP}"
{overlay}
# ROOT python bindings are not on the default PYTHONPATH of the release
export PYTHONPATH="{P.ROOT_LIB}:${{PYTHONPATH:-}}"
export LD_LIBRARY_PATH="{P.ROOT_LIB}:${{LD_LIBRARY_PATH:-}}"
export XRD_STREAMTIMEOUT={P.XRD_STREAMTIMEOUT}

echo "[recon] impl={impl} evtmax={evtmax}"
echo "[recon] input-list: {input_list}"
python "${{TUTORIALROOT}}/share/tut_rtraw2rec.py" \\
    --loglevel Info --evtmax {evtmax} \\
    --input-list "{input_list}" \\
    --output "{out_root}" \\
    {flags}

# --- verify: the output must carry the OMILREC vertex tree (MySimpleTag's
# input). Exit non-zero if missing so the audit catches silent failures.
python - "{out_root}" <<'PY'
import sys
import ROOT
f = ROOT.TFile(sys.argv[1])
if not f or f.IsZombie():
    raise SystemExit("[verify] FAILED: cannot open output")
t = f.Get("Event/CdVertexRecOMILREC/CdVertexRecEvt")
n = t.GetEntries() if t else -1
print(f"[verify] CdVertexRecOMILREC entries: {{n}}")
if n <= 0:
    raise SystemExit("[verify] FAILED: no CdVertexRecOMILREC entries")
PY
echo "[recon] done: {out_root}"
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("run", type=int)
    ap.add_argument("--input-list", required=True)
    ap.add_argument("--out-root", required=True, help="output ESD .root path")
    ap.add_argument("--evtmax", type=int, default=P.DEFAULT_EVTMAX)
    ap.add_argument("--impl", choices=["omilrecv2", "baseline"],
                    default=P.DEFAULT_IMPL)
    ap.add_argument("--work-dir", required=True, help="dir for wrapper+log")
    args = ap.parse_args()

    work = Path(args.work_dir)
    work.mkdir(parents=True, exist_ok=True)
    wrapper = work / f"recon_RUN{args.run}_{args.impl}.sh"
    wrapper.write_text(build_wrapper(args.impl, args.input_list,
                                     args.out_root, args.evtmax))
    wrapper.chmod(0o755)

    log = work / f"recon_RUN{args.run}_{args.impl}.log"
    t0 = time.time()
    with open(log, "w") as lf:
        rc = subprocess.call(["bash", str(wrapper)], stdout=lf,
                             stderr=subprocess.STDOUT)
    dt = time.time() - t0
    print(f"[Info] recon rc={rc}  elapsed={dt:.1f}s  log={log}")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
